modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors="アドニス、疏影"
description = "添加了一些新机器和简化配方，结构与材质由疏影提供"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId = "gtlcore"
mandatory = true
versionRange = "[1.2.2.7-fix6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "sgjourney"
mandatory = true
versionRange = "[0.6.44,)"
ordering = "AFTER"
side = "BOTH"